export enum Friend {
  One = 0,
  Ten = 1,
  TwentyFive = 2,
  Fifty = 3,
  OneHundred = 4,
  TwoHundred = 5,
  FiveHundred = 6,
  OneThousand = 7,
  TwoTHousand = 8,
  FiveThousand = 9,
  TenThousand = 10,
  FiftyThousand = 11,
  OneHundredThousand = 12,
}
