export enum Vote {
  Min = 200,
  Max= 265,

  UpVoterTen = 200,
  UpVoterFifty = 201,
  UpVoterTwoHundred = 202,
  UpVoterFiveHundred = 203,
  UpVoterOneThousand = 204,
  UpVoterTwoThousand = 205,
  UpVoterFiveThousand = 206,
  UpVoterTenThousand = 207,
  UpVoterTwentyFiveThousand = 208,
  UpVoterFiftyThousand = 209,
  UpVoterOneHundredThousand = 210,

  DownVoterTen = 211,
  DownVoterFifty = 212,
  DownVoterTwoHundred = 213,
  DownVoterFiveHundred = 214,
  DownVoterOneThousand = 215,
  DownVoterTwoThousand = 216,
  DownVoterFiveThousand = 217,
  DownVoterTenThousand = 218,
  DownVoterTwentyFiveThousand = 219,
  DownVoterFiftyThousand = 220,
  DownVoterOneHundredThousand = 221,

  UpVotedTen = 222,
  UpVotedFifty = 223,
  UpVotedTwoHundred = 224,
  UpVotedFiveHundred = 225,
  UpVotedOneThousand = 226,
  UpVotedTwoThousand = 227,
  UpVotedFiveThousand = 228,
  UpVotedTenThousand = 229,
  UpVotedTwentyFiveThousand = 230,
  UpVotedFiftyThousand = 231,
  UpVotedOneHundredThousand = 232,

  DownVotedTen = 233,
  DownVotedFifty = 234,
  DownVotedTwoHundred = 235,
  DownVotedFiveHundred = 236,
  DownVotedOneThousand = 237,
  DownVotedTwoThousand = 238,
  DownVotedFiveThousand = 239,
  DownVotedTenThousand = 240,
  DownVotedTwentyFiveThousand = 241,
  DownVotedFiftyThousand = 242,
  DownVotedOneHundredThousand = 243,

  HubUpVoteTen = 244,
  HubUpVoteFifty = 245,
  HubUpVoteTwoHundred = 246,
  HubUpVoteFiveHundred = 247,
  HubUpVoteOneThousand = 248,
  HubUpVoteTwoThousand = 249,
  HubUpVoteFiveThousand = 250,
  HubUpVoteTenThousand = 251,
  HubUpVoteTwentyFiveThousand = 252,
  HubUpVoteFiftyThousand = 253,
  HubUpVoteOneHundredThousand = 254,

  HubDownVoteTen = 255,
  HubDownVoteFifty = 256,
  HubDownVoteTwoHundred = 257,
  HubDownVoteFiveHundred = 258,
  HubDownVoteOneThousand = 259,
  HubDownVoteTwoThousand = 260,
  HubDownVoteFiveThousand = 261,
  HubDownVoteTenThousand = 262,
  HubDownVoteTwentyFiveThousand = 263,
  HubDownVoteFiftyThousand = 264,
  HubDownVoteOneHundredThousand = 265,
}
