export enum Vote {
  Min = "a0",
  Max = "b4",

  IMin = 620,
  IMax= 685,

  UpVoterTen = "a0",
  UpVoterFifty = "a1",
  UpVoterTwoHundred = "a2",
  UpVoterFiveHundred = "a3",
  UpVoterOneThousand = "a4",
  UpVoterTwoThousand = "a5",
  UpVoterFiveThousand = "a6",
  UpVoterTenThousand = "a7",
  UpVoterTwentyFiveThousand = "a8",
  UpVoterFiftyThousand = "a9",
  UpVoterOneHundredThousand = "aa",

  DownVoterTen = "ab",
  DownVoterFifty = "ac",
  DownVoterTwoHundred = "ad",
  DownVoterFiveHundred = "ae",
  DownVoterOneThousand = "af",
  DownVoterTwoThousand = "ag",
  DownVoterFiveThousand = "ah",
  DownVoterTenThousand = "ai",
  DownVoterTwentyFiveThousand = "aj",
  DownVoterFiftyThousand = "ak",
  DownVoterOneHundredThousand = "al",

  UpVotedTen = "am",
  UpVotedFifty = "an",
  UpVotedTwoHundred = "ao",
  UpVotedFiveHundred = "ap",
  UpVotedOneThousand = "aq",
  UpVotedTwoThousand = "ar",
  UpVotedFiveThousand = "as",
  UpVotedTenThousand = "at",
  UpVotedTwentyFiveThousand = "au",
  UpVotedFiftyThousand = "av",
  UpVotedOneHundredThousand = "aw",

  DownVotedTen = "ax",
  DownVotedFifty = "ay",
  DownVotedTwoHundred = "az",
  DownVotedFiveHundred = "aA",
  DownVotedOneThousand = "aB",
  DownVotedTwoThousand = "aC",
  DownVotedFiveThousand = "aD",
  DownVotedTenThousand = "aE",
  DownVotedTwentyFiveThousand = "aF",
  DownVotedFiftyThousand = "aG",
  DownVotedOneHundredThousand = "aH",

  HubUpVoteTen = "aI",
  HubUpVoteFifty = "aJ",
  HubUpVoteTwoHundred = "aK",
  HubUpVoteFiveHundred = "aL",
  HubUpVoteOneThousand = "aM",
  HubUpVoteTwoThousand = "aN",
  HubUpVoteFiveThousand = "aO",
  HubUpVoteTenThousand = "aP",
  HubUpVoteTwentyFiveThousand = "aQ",
  HubUpVoteFiftyThousand = "aR",
  HubUpVoteOneHundredThousand = "aS",

  HubDownVoteTen = "aT",
  HubDownVoteFifty = "aU",
  HubDownVoteTwoHundred = "aV",
  HubDownVoteFiveHundred = "aW",
  HubDownVoteOneThousand = "aX",
  HubDownVoteTwoThousand = "aY",
  HubDownVoteFiveThousand = "aZ",
  HubDownVoteTenThousand = "b0",
  HubDownVoteTwentyFiveThousand = "b1",
  HubDownVoteFiftyThousand = "b2",
  HubDownVoteOneHundredThousand = "b3",
}
