export enum Vote {
  UpVoterTen = 33,
  UpVoterFifty = 34,
  UpVoterTwoHundred = 35,
  UpVoterFiveHundred = 36,
  UpVoterOneThousand = 37,
  UpVoterTwoThousand = 38,
  UpVoterFiveThousand = 39,
  UpVoterTenThousand = 40,
  UpVoterTwentyFiveThousand = 41,
  UpVoterFiftyThousand = 42,
  UpVoterOneHundredThousand = 43,

  DownVoterTen = 44,
  DownVoterFifty = 45,
  DownVoterTwoHundred = 46,
  DownVoterFiveHundred = 47,
  DownVoterOneThousand = 48,
  DownVoterTwoThousand = 49,
  DownVoterFiveThousand = 50,
  DownVoterTenThousand = 51,
  DownVoterTwentyFiveThousand = 52,
  DownVoterFiftyThousand = 53,
  DownVoterOneHundredThousand = 54,

  UpVotedTen = 55,
  UpVotedFifty = 56,
  UpVotedTwoHundred = 57,
  UpVotedFiveHundred = 58,
  UpVotedOneThousand = 59,
  UpVotedTwoThousand = 60,
  UpVotedFiveThousand = 61,
  UpVotedTenThousand = 62,
  UpVotedTwentyFiveThousand = 63,
  UpVotedFiftyThousand = 64,
  UpVotedOneHundredThousand = 65,

  DownVotedTen = 66,
  DownVotedFifty = 67,
  DownVotedTwoHundred = 68,
  DownVotedFiveHundred = 69,
  DownVotedOneThousand = 70,
  DownVotedTwoThousand = 71,
  DownVotedFiveThousand = 72
  DownVotedTenThousand = 73,
  DownVotedTwentyFiveThousand = 74,
  DownVotedFiftyThousand = 75,
  DownVotedOneHundredThousand = 76,

  HubUpVoteTen = 101,
  HubUpVoteFifty = 102,
  HubUpVoteTwoHundred = 103,
  HubUpVoteFiveHundred = 104,
  HubUpVoteOneThousand = 105,
  HubUpVoteTwoThousand = 106,
  HubUpVoteFiveThousand = 107,
  HubUpVoteTenThousand = 108,
  HubUpVoteTwentyFiveThousand = 109,
  HubUpVoteFiftyThousand = 110,
  HubUpVoteOneHundredThousand = 111,

  HubDownVoteTen = 112,
  HubDownVoteFifty = 113,
  HubDownVoteTwoHundred = 114,
  HubDownVoteFiveHundred = 115,
  HubDownVoteOneThousand = 116,
  HubDownVoteTwoThousand = 117,
  HubDownVoteFiveThousand = 118,
  HubDownVoteTenThousand = 119,
  HubDownVoteTwentyFiveThousand = 120,
  HubDownVoteFiftyThousand = 121,
  HubDownVoteOneHundredThousand = 122,
}
